import os
import platform
from typing import Optional
from mvpc.backends.registry import BackendRegistry
from mvpc.policy import PolicyLevel, get_policy, evaluate_attestation
from mvpc.claim import Claim, create_claim, load_claim_from_yaml
from mvpc.provenance import Provenance, SourceType
from mvpc.witness import generate_witness

class VerificationEngine:
    def __init__(self, policy_level: PolicyLevel, registry: BackendRegistry):
        self.policy = get_policy(policy_level)
        self.registry = registry

    def _get_environment(self) -> dict:
        return {
            "os": os.name,
            "platform": platform.platform(),
            "python_version": platform.python_version()
        }

    def verify_artifact(self, path: str, statement: Optional[str] = None, origin: Optional[SourceType] = None) -> Claim:
        backend = self.registry.get_backend(path)
        
        # Run audit on backend
        findings, evidence, coverage = backend.audit(path)
        
        # Evaluate policy
        attestation_state = evaluate_attestation(findings, coverage, self.policy)
        
        # Create claim
        stmt = statement or f"Artifact {os.path.basename(path)} satisfies policy level {self.policy.level.name}"
        org = origin or SourceType.UNKNOWN
        
        prov = Provenance(
            source_type=org,
            origin_description="Auto-generated by engine for artifact",
            timestamp=evidence[0].timestamp if evidence else "unknown"
        )
        
        claim = create_claim(
            statement=stmt,
            origin=org,
            scope="file",
            definitions={},
            provenance=prov
        )
        
        claim.evidence = evidence
        claim.findings = findings
        claim.coverage = coverage
        claim.attestation_state = attestation_state
        
        # Generate witness and attach to claim metadata
        witness = generate_witness(claim, self.policy, self._get_environment())
        if not claim.provenance.metadata:
            claim.provenance.metadata = {}
        claim.provenance.metadata['witness'] = witness.to_dict()
        
        return claim

    def verify_claim(self, claim_yaml_path: str) -> Claim:
        # Simplistic stub for claim manifest verification
        claim = load_claim_from_yaml(claim_yaml_path)
        return claim
